language: node_js

node_js:
  - '9'

cache:
  directories:
    - 'node_modules'

addons:
  sauce_connect: true

before_script:
  - 'npm run release:serve &'

script: 'npm run release:build && npm run test:sauce'
